#include "hint.h"

const char *HINT_MODE_JS =
"(function() {\n"
"    if (window.__peregrine_hints_active) return;\n"
"    window.__peregrine_hints_active = true;\n"
"    window.__peregrine_typed = '';\n"
"    \n"
"    const hintChars = 'asdfghjkl';\n"
"    \n"
"    function generateHintLabels(count) {\n"
"        if (count <= hintChars.length) {\n"
"            return hintChars.split('').slice(0, count);\n"
"        }\n"
"        let labels = [];\n"
"        for (let i = 0; i < hintChars.length; i++) {\n"
"            for (let j = 0; j < hintChars.length; j++) {\n"
"                labels.push(hintChars[i] + hintChars[j]);\n"
"                if (labels.length >= count) return labels;\n"
"            }\n"
"        }\n"
"        return labels;\n"
"    }\n"
"    \n"
"    function isElementVisible(el, rect) {\n"
"        if (rect.width === 0 || rect.height === 0) return false;\n"
"        if (rect.bottom < 0 || rect.right < 0 || rect.top > window.innerHeight || rect.left > window.innerWidth) return false;\n"
"        const style = window.getComputedStyle(el);\n"
"        if (style.visibility === 'hidden' || style.opacity === '0' || style.display === 'none') return false;\n"
"        return true;\n"
"    }\n"
"    \n"
"    const selector = \"a, button, input:not([type='hidden']), textarea, select, [tabindex], [onclick], [role='button'], [role='link']\";\n"
"    const allElements = document.querySelectorAll(selector);\n"
"    const visibleElements = [];\n"
"    \n"
"    for (let el of allElements) {\n"
"        const rect = el.getBoundingClientRect();\n"
"        if (isElementVisible(el, rect)) {\n"
"            visibleElements.push({ el: el, rect: rect });\n"
"        }\n"
"    }\n"
"    \n"
"    const labels = generateHintLabels(visibleElements.length);\n"
"    const container = document.createElement('div');\n"
"    container.id = '__peregrine_hint_container';\n"
"    container.style.position = 'absolute';\n"
"    container.style.top = '0';\n"
"    container.style.left = '0';\n"
"    container.style.width = '100%';\n"
"    container.style.height = '100%';\n"
"    container.style.pointerEvents = 'none';\n"
"    container.style.zIndex = '2147483647';\n"
"    document.body.appendChild(container);\n"
"    \n"
"    window.__peregrine_hint_map = {};\n"
"    window.__peregrine_hint_items = [];\n"
"    \n"
"    visibleElements.forEach((item, index) => {\n"
"        if (index >= labels.length) return;\n"
"        const label = labels[index];\n"
"        window.__peregrine_hint_map[label] = item.el;\n"
"        \n"
"        const hintDiv = document.createElement('div');\n"
"        hintDiv.className = 'peregrine-hint';\n"
"        hintDiv.textContent = label.toUpperCase();\n"
"        hintDiv.style.position = 'absolute';\n"
"        hintDiv.style.left = (window.scrollX + item.rect.left) + 'px';\n"
"        hintDiv.style.top = (window.scrollY + item.rect.top) + 'px';\n"
"        hintDiv.style.background = '#ffff00';\n"
"        hintDiv.style.color = '#000000';\n"
"        hintDiv.style.border = '1px solid #d4a017';\n"
"        hintDiv.style.padding = '1px 3px';\n"
"        hintDiv.style.fontSize = '11px';\n"
"        hintDiv.style.fontWeight = 'bold';\n"
"        hintDiv.style.fontFamily = 'monospace';\n"
"        hintDiv.style.boxShadow = '0 2px 4px rgba(0,0,0,0.3)';\n"
"        hintDiv.style.borderRadius = '2px';\n"
"        hintDiv.style.zIndex = '2147483647';\n"
"        container.appendChild(hintDiv);\n"
"        \n"
"        window.__peregrine_hint_items.push({ hint: hintDiv, text: label });\n"
"    });\n"
"    \n"
"    window.__peregrine_handle_char = function(ch) {\n"
"        ch = ch.toLowerCase();\n"
"        window.__peregrine_typed += ch;\n"
"        const typed = window.__peregrine_typed;\n"
"        \n"
"        if (window.__peregrine_hint_map[typed]) {\n"
"            const target = window.__peregrine_hint_map[typed];\n"
"            window.__peregrine_exit_hint_mode();\n"
"            target.focus();\n"
"            target.click();\n"
"            return 'activated';\n"
"        }\n"
"        \n"
"        let matchFound = false;\n"
"        const items = window.__peregrine_hint_items;\n"
"        for (let i = 0; i < items.length; i++) {\n"
"            const item = items[i];\n"
"            if (item.text.startsWith(typed)) {\n"
"                matchFound = true;\n"
"                item.hint.style.display = 'inline-block';\n"
"                const matchedPart = item.text.substring(0, typed.length);\n"
"                const restPart = item.text.substring(typed.length);\n"
"                item.hint.innerHTML = `<span style=\"color: #ff0000;\">${matchedPart.toUpperCase()}</span>${restPart.toUpperCase()}`;\n"
"            } else {\n"
"                item.hint.style.display = 'none';\n"
"            }\n"
"        }\n"
"        \n"
"        if (!matchFound) {\n"
"            window.__peregrine_exit_hint_mode();\n"
"            return 'cancelled';\n"
"        }\n"
"        return 'continue';\n"
"    };\n"
"    \n"
"    window.__peregrine_exit_hint_mode = function() {\n"
"        if (!window.__peregrine_hints_active) return;\n"
"        window.__peregrine_hints_active = false;\n"
"        const c = document.getElementById('__peregrine_hint_container');\n"
"        if (c) c.remove();\n"
"        delete window.__peregrine_hint_container;\n"
"        delete window.__peregrine_hint_map;\n"
"        delete window.__peregrine_hint_items;\n"
"        delete window.__peregrine_handle_char;\n"
"        delete window.__peregrine_exit_hint_mode;\n"
"        delete window.__peregrine_typed;\n"
"    };\n"
"})();";

void hint_enter_mode(WebKitWebView *web_view) {
    if (!web_view) return;
    webkit_web_view_evaluate_javascript(web_view, HINT_MODE_JS, -1, NULL, NULL, NULL, NULL, NULL);
}

void hint_exit_mode(WebKitWebView *web_view) {
    if (!web_view) return;
    webkit_web_view_evaluate_javascript(web_view, "if (window.__peregrine_exit_hint_mode) window.__peregrine_exit_hint_mode();", -1, NULL, NULL, NULL, NULL, NULL);
}
