#include "ytblock.h"

const char *YTBLOCK_JS =
"console.log('ytblock active');\n"
"(function() {\n"
"    function stripAds(obj) {\n"
"        if (obj && typeof obj === 'object') {\n"
"            delete obj.playerAds;\n"
"            delete obj.adPlacements;\n"
"            delete obj.adSlots;\n"
"            delete obj.adBreakHeartbeatParams;\n"
"        }\n"
"        return obj;\n"
"    }\n"
"\n"
"    let _ytInitialPlayerResponse;\n"
"    Object.defineProperty(window, 'ytInitialPlayerResponse', {\n"
"        configurable: true,\n"
"        get() { return _ytInitialPlayerResponse; },\n"
"        set(value) {\n"
"            try {\n"
"                console.log('ytblock raw keys', Object.keys(value || {}));\n"
"                if (value && value.playerAds) console.log('ytblock found playerAds', value.playerAds);\n"
"                if (value && value.adPlacements) console.log('ytblock found adPlacements', value.adPlacements);\n"
"                stripAds(value);\n"
"            } catch (e) {}\n"
"            _ytInitialPlayerResponse = value;\n"
"        }\n"
"    });\n"
"\n"
"    const origFetch = window.fetch;\n"
"    window.fetch = function(...args) {\n"
"        const url = (args[0] && args[0].url) || args[0];\n"
"        const isPlayerRequest = typeof url === 'string' && url.includes('/youtubei/v1/player');\n"
"        const promise = origFetch.apply(this, args);\n"
"        if (!isPlayerRequest) return promise;\n"
"        return promise.then(async (response) => {\n"
"            try {\n"
"                const data = await response.clone().json();\n"
"                stripAds(data);\n"
"                return new Response(JSON.stringify(data), {\n"
"                    status: response.status,\n"
"                    statusText: response.statusText,\n"
"                    headers: response.headers\n"
"                });\n"
"            } catch (e) {\n"
"                return response;\n"
"            }\n"
"        });\n"
"    };\n"
"})();";
