#include "ytblock.h"

const char *YTBLOCK_JS =
"(function() {\n"
"    console.log('ytblock active');\n"
"\n"
"    function stripAds(obj) {\n"
"        if (obj && typeof obj === 'object') {\n"
"            delete obj.playerAds;\n"
"            delete obj.adPlacements;\n"
"            delete obj.adSlots;\n"
"            delete obj.adBreakHeartbeatParams;\n"
"        }\n"
"        return obj;\n"
"    }\n"
"\n"
"    let _ytInitialPlayerResponse;\n"
"    Object.defineProperty(window, 'ytInitialPlayerResponse', {\n"
"        configurable: true,\n"
"        get() { return _ytInitialPlayerResponse; },\n"
"        set(value) {\n"
"            try {\n"
"                console.log('ytblock raw keys', Object.keys(value || {}));\n"
"                if (value && value.playerAds) console.log('ytblock found playerAds', value.playerAds);\n"
"                if (value && value.adPlacements) console.log('ytblock found adPlacements', value.adPlacements);\n"
"                stripAds(value);\n"
"            } catch (e) {}\n"
"            _ytInitialPlayerResponse = value;\n"
"        }\n"
"    });\n"
"\n"
"const origFetch = window.fetch;\n"
"window.fetch = function(...args) {\n"
    "    const url = (args[0] && args[0].url) || args[0];\n"
"    const isPlayerRequest = typeof url === 'string' && url.includes('/youtubei/v1/player');\n"
"    const promise = origFetch.apply(this, args);\n"
"    if (!isPlayerRequest) return promise;\n"
"    console.log('ytblock patching player fetch', url);\n"
"    return promise.then(async (response) => {\n"
"        try {\n"
"            const data = await response.clone().json();\n"
"            console.log('ytblock player response keys before', Object.keys(data));\n"
"            stripAds(data);\n"
"            console.log('ytblock player response keys after', Object.keys(data));\n"
    "            return new Response(JSON.stringify(data), {\n"
"                status: response.status,\n"
"                statusText: response.statusText,\n"
"                headers: response.headers\n"
"            });\n"
"        } catch (e) {\n"
"            console.error('ytblock patch failed', e);\n"
"            return response;\n"
"        }\n"
"    });\n"
"};\n"
"    const origOpen = XMLHttpRequest.prototype.open;\n"
"    XMLHttpRequest.prototype.open = function(method, url, ...rest) {\n"
"        if (typeof url === 'string' && url.includes('/youtubei/v1/player')) {\n"
"            this.addEventListener('readystatechange', function() {\n"
"                if (this.readyState === 4) {\n"
"                    try {\n"
"                        const data = JSON.parse(this.responseText);\n"
"                        stripAds(data);\n"
"                        const patched = JSON.stringify(data);\n"
"                        Object.defineProperty(this, 'responseText', { value: patched, configurable: true });\n"
"                        Object.defineProperty(this, 'response', { value: patched, configurable: true });\n"
"                    } catch (e) {}\n"
"                }\n"
"            });\n"
"        }\n"
"        return origOpen.call(this, method, url, ...rest);\n"
"    };\n"
"\n"
"    const origJSONParse = JSON.parse;\n"
"    JSON.parse = function(...args) {\n"
"        const result = origJSONParse.apply(this, args);\n"
"        try {\n"
"            if (result && typeof result === 'object' && ('videoDetails' in result || 'streamingData' in result)) {\n"
"                stripAds(result);\n"
"            }\n"
"        } catch (e) {}\n"
"        return result;\n"
"    };\n"
"})();";
